global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: monitoring-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - monitoring-service:3016

  - job_name: conversation-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - conversation-service:3005

  - job_name: call-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - call-service:3007

  - job_name: notification-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - notification-service:3015

  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth-service:3017

  - job_name: user-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - user-service:3018

  - job_name: rabbitmq-reels
    metrics_path: /metrics/detailed
    params:
      family:
        - queue_coarse_metrics
        - queue_consumer_count
        - channel_queue_metrics
        - channel_queue_exchange_metrics
    static_configs:
      - targets:
          - rabbitmq:15692
    metric_relabel_configs:
      - source_labels: [__name__, queue]
        separator: ';'
        regex: 'up;|rabbitmq_detailed_.*;reel_(media|index)_.+'
        action: keep

  - job_name: rabbitmq-auth-user
    metrics_path: /metrics/detailed
    params:
      family:
        - queue_coarse_metrics
        - queue_consumer_count
    static_configs:
      - targets:
          - rabbitmq:15692
    metric_relabel_configs:
      - source_labels: [__name__, queue]
        separator: ';'
        regex: 'up;|rabbitmq_detailed_.*;(auth_queue|user_queue)'
        action: keep

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
